import { CreateLanguageDto } from 'src/dtos/CreateLanguage.dto';

export function getLanguages(): CreateLanguageDto[] {
  return [
    {
      code: 'aa',
      name: 'Afar',
      native: 'Afar',
      rtl: 0,
    },
    {
      code: 'ab',
      name: 'Abkhazian',
      native: 'Аҧсуа',
      rtl: 0,
    },
    {
      code: 'af',
      name: 'Afrikaans',
      native: 'Afrikaans',
      rtl: 0,
    },
    {
      code: 'ak',
      name: 'Akan',
      native: 'Akana',
      rtl: 0,
    },
    {
      code: 'am',
      name: 'Amharic',
      native: 'አማርኛ',
      rtl: 0,
    },
    {
      code: 'an',
      name: 'Aragonese',
      native: 'Aragonés',
      rtl: 0,
    },
    {
      code: 'ar',
      name: 'Arabic',
      native: 'العربية',
      rtl: 1,
    },
    {
      code: 'as',
      name: 'Assamese',
      native: 'অসমীয়া',
      rtl: 0,
    },
    {
      code: 'av',
      name: 'Avar',
      native: 'Авар',
      rtl: 0,
    },
    {
      code: 'ay',
      name: 'Aymara',
      native: 'Aymar',
      rtl: 0,
    },
    {
      code: 'az',
      name: 'Azerbaijani',
      native: 'Azərbaycanca / آذربايجان',
      rtl: 0,
    },
    {
      code: 'ba',
      name: 'Bashkir',
      native: 'Башҡорт',
      rtl: 0,
    },
    {
      code: 'be',
      name: 'Belarusian',
      native: 'Беларуская',
      rtl: 0,
    },
    {
      code: 'bg',
      name: 'Bulgarian',
      native: 'Български',
      rtl: 0,
    },
    {
      code: 'bh',
      name: 'Bihari',
      native: 'भोजपुरी',
      rtl: 0,
    },
    {
      code: 'bi',
      name: 'Bislama',
      native: 'Bislama',
      rtl: 0,
    },
    {
      code: 'bm',
      name: 'Bambara',
      native: 'Bamanankan',
      rtl: 0,
    },
    {
      code: 'bn',
      name: 'Bengali',
      native: 'বাংলা',
      rtl: 0,
    },
    {
      code: 'bo',
      name: 'Tibetan',
      native: 'བོད་ཡིག / Bod skad',
      rtl: 0,
    },
    {
      code: 'br',
      name: 'Breton',
      native: 'Brezhoneg',
      rtl: 0,
    },
    {
      code: 'bs',
      name: 'Bosnian',
      native: 'Bosanski',
      rtl: 0,
    },
    {
      code: 'ca',
      name: 'Catalan',
      native: 'Català',
      rtl: 0,
    },
    {
      code: 'ce',
      name: 'Chechen',
      native: 'Нохчийн',
      rtl: 0,
    },
    {
      code: 'ch',
      name: 'Chamorro',
      native: 'Chamoru',
      rtl: 0,
    },
    {
      code: 'co',
      name: 'Corsican',
      native: 'Corsu',
      rtl: 0,
    },
    {
      code: 'cr',
      name: 'Cree',
      native: 'Nehiyaw',
      rtl: 0,
    },
    {
      code: 'cs',
      name: 'Czech',
      native: 'Česky',
      rtl: 0,
    },
    {
      code: 'cu',
      name: 'Old Church Slavonic / Old Bulgarian',
      native: 'словѣньскъ / slověnĭskŭ',
      rtl: 0,
    },
    {
      code: 'cv',
      name: 'Chuvash',
      native: 'Чăваш',
      rtl: 0,
    },
    {
      code: 'cy',
      name: 'Welsh',
      native: 'Cymraeg',
      rtl: 0,
    },
    {
      code: 'da',
      name: 'Danish',
      native: 'Dansk',
      rtl: 0,
    },
    {
      code: 'de',
      name: 'German',
      native: 'Deutsch',
      rtl: 0,
    },
    {
      code: 'dv',
      name: 'Divehi',
      native: 'ދިވެހިބަސް',
      rtl: 1,
    },
    {
      code: 'dz',
      name: 'Dzongkha',
      native: 'ཇོང་ཁ',
      rtl: 0,
    },
    {
      code: 'ee',
      name: 'Ewe',
      native: 'Ɛʋɛ',
      rtl: 0,
    },
    {
      code: 'el',
      name: 'Greek',
      native: 'Ελληνικά',
      rtl: 0,
    },
    {
      code: 'en',
      name: 'English',
      native: 'English',
      rtl: 0,
    },
    {
      code: 'eo',
      name: 'Esperanto',
      native: 'Esperanto',
      rtl: 0,
    },
    {
      code: 'es',
      name: 'Spanish',
      native: 'Español',
      rtl: 0,
    },
    {
      code: 'et',
      name: 'Estonian',
      native: 'Eesti',
      rtl: 0,
    },
    {
      code: 'eu',
      name: 'Basque',
      native: 'Euskara',
      rtl: 0,
    },
    {
      code: 'fa',
      name: 'Persian',
      native: 'فارسی',
      rtl: 1,
    },
    {
      code: 'ff',
      name: 'Peul',
      native: 'Fulfulde',
      rtl: 0,
    },
    {
      code: 'fi',
      name: 'Finnish',
      native: 'Suomi',
      rtl: 0,
    },
    {
      code: 'fj',
      name: 'Fijian',
      native: 'Na Vosa Vakaviti',
      rtl: 0,
    },
    {
      code: 'fo',
      name: 'Faroese',
      native: 'Føroyskt',
      rtl: 0,
    },
    {
      code: 'fr',
      name: 'French',
      native: 'Français',
      rtl: 0,
    },
    {
      code: 'fy',
      name: 'West Frisian',
      native: 'Frysk',
      rtl: 0,
    },
    {
      code: 'ga',
      name: 'Irish',
      native: 'Gaeilge',
      rtl: 0,
    },
    {
      code: 'gd',
      name: 'Scottish Gaelic',
      native: 'Gàidhlig',
      rtl: 0,
    },
    {
      code: 'gl',
      name: 'Galician',
      native: 'Galego',
      rtl: 0,
    },
    {
      code: 'gn',
      name: 'Guarani',
      native: "Avañe'ẽ",
      rtl: 0,
    },
    {
      code: 'gu',
      name: 'Gujarati',
      native: 'ગુજરાતી',
      rtl: 0,
    },
    {
      code: 'gv',
      name: 'Manx',
      native: 'Gaelg',
      rtl: 0,
    },
    {
      code: 'ha',
      name: 'Hausa',
      native: 'هَوُسَ',
      rtl: 1,
    },
    {
      code: 'he',
      name: 'Hebrew',
      native: 'עברית',
      rtl: 1,
    },
    {
      code: 'hi',
      name: 'Hindi',
      native: 'हिन्दी',
      rtl: 0,
    },
    {
      code: 'ho',
      name: 'Hiri Motu',
      native: 'Hiri Motu',
      rtl: 0,
    },
    {
      code: 'hr',
      name: 'Croatian',
      native: 'Hrvatski',
      rtl: 0,
    },
    {
      code: 'ht',
      name: 'Haitian',
      native: 'Krèyol ayisyen',
      rtl: 0,
    },
    {
      code: 'hu',
      name: 'Hungarian',
      native: 'Magyar',
      rtl: 0,
    },
    {
      code: 'hy',
      name: 'Armenian',
      native: 'Հայերեն',
      rtl: 0,
    },
    {
      code: 'hz',
      name: 'Herero',
      native: 'Otsiherero',
      rtl: 0,
    },
    {
      code: 'ia',
      name: 'Interlingua',
      native: 'Interlingua',
      rtl: 0,
    },
    {
      code: 'id',
      name: 'Indonesian',
      native: 'Bahasa Indonesia',
      rtl: 0,
    },
    {
      code: 'ie',
      name: 'Interlingue',
      native: 'Interlingue',
      rtl: 0,
    },
    {
      code: 'ig',
      name: 'Igbo',
      native: 'Igbo',
      rtl: 0,
    },
    {
      code: 'ii',
      name: 'Sichuan Yi',
      native: 'ꆇꉙ / 四川彝语',
      rtl: 0,
    },
    {
      code: 'ik',
      name: 'Inupiak',
      native: 'Iñupiak',
      rtl: 0,
    },
    {
      code: 'io',
      name: 'Ido',
      native: 'Ido',
      rtl: 0,
    },
    {
      code: 'is',
      name: 'Icelandic',
      native: 'Íslenska',
      rtl: 0,
    },
    {
      code: 'it',
      name: 'Italian',
      native: 'Italiano',
      rtl: 0,
    },
    {
      code: 'iu',
      name: 'Inuktitut',
      native: 'ᐃᓄᒃᑎᑐᑦ',
      rtl: 0,
    },
    {
      code: 'ja',
      name: 'Japanese',
      native: '日本語',
      rtl: 0,
    },
    {
      code: 'jv',
      name: 'Javanese',
      native: 'Basa Jawa',
      rtl: 0,
    },
    {
      code: 'ka',
      name: 'Georgian',
      native: 'ქართული',
      rtl: 0,
    },
    {
      code: 'kg',
      name: 'Kongo',
      native: 'KiKongo',
      rtl: 0,
    },
    {
      code: 'ki',
      name: 'Kikuyu',
      native: 'Gĩkũyũ',
      rtl: 0,
    },
    {
      code: 'kj',
      name: 'Kuanyama',
      native: 'Kuanyama',
      rtl: 0,
    },
    {
      code: 'kk',
      name: 'Kazakh',
      native: 'Қазақша',
      rtl: 0,
    },
    {
      code: 'kl',
      name: 'Greenlandic',
      native: 'Kalaallisut',
      rtl: 0,
    },
    {
      code: 'km',
      name: 'Cambodian',
      native: 'ភាសាខ្មែរ',
      rtl: 0,
    },
    {
      code: 'kn',
      name: 'Kannada',
      native: 'ಕನ್ನಡ',
      rtl: 0,
    },
    {
      code: 'ko',
      name: 'Korean',
      native: '한국어',
      rtl: 0,
    },
    {
      code: 'kr',
      name: 'Kanuri',
      native: 'Kanuri',
      rtl: 0,
    },
    {
      code: 'ks',
      name: 'Kashmiri',
      native: 'कश्मीरी / كشميري',
      rtl: 1,
    },
    {
      code: 'ku',
      name: 'Kurdish',
      native: 'Kurdî / كوردی',
      rtl: 1,
    },
    {
      code: 'kv',
      name: 'Komi',
      native: 'Коми',
      rtl: 0,
    },
    {
      code: 'kw',
      name: 'Cornish',
      native: 'Kernewek',
      rtl: 0,
    },
    {
      code: 'ky',
      name: 'Kirghiz',
      native: 'Kırgızca / Кыргызча',
      rtl: 0,
    },
    {
      code: 'la',
      name: 'Latin',
      native: 'Latina',
      rtl: 0,
    },
    {
      code: 'lb',
      name: 'Luxembourgish',
      native: 'Lëtzebuergesch',
      rtl: 0,
    },
    {
      code: 'lg',
      name: 'Ganda',
      native: 'Luganda',
      rtl: 0,
    },
    {
      code: 'li',
      name: 'Limburgian',
      native: 'Limburgs',
      rtl: 0,
    },
    {
      code: 'ln',
      name: 'Lingala',
      native: 'Lingála',
      rtl: 0,
    },
    {
      code: 'lo',
      name: 'Laotian',
      native: 'ລາວ / Pha xa lao',
      rtl: 0,
    },
    {
      code: 'lt',
      name: 'Lithuanian',
      native: 'Lietuvių',
      rtl: 0,
    },
    {
      code: 'lu',
      name: 'Luba-Katanga',
      native: 'Tshiluba',
      rtl: 0,
    },
    {
      code: 'lv',
      name: 'Latvian',
      native: 'Latviešu',
      rtl: 0,
    },
    {
      code: 'mg',
      name: 'Malagasy',
      native: 'Malagasy',
      rtl: 0,
    },
    {
      code: 'mh',
      name: 'Marshallese',
      native: 'Kajin Majel / Ebon',
      rtl: 0,
    },
    {
      code: 'mi',
      name: 'Maori',
      native: 'Māori',
      rtl: 0,
    },
    {
      code: 'mk',
      name: 'Macedonian',
      native: 'Македонски',
      rtl: 0,
    },
    {
      code: 'ml',
      name: 'Malayalam',
      native: 'മലയാളം',
      rtl: 0,
    },
    {
      code: 'mn',
      name: 'Mongolian',
      native: 'Монгол',
      rtl: 0,
    },
    {
      code: 'mo',
      name: 'Moldovan',
      native: 'Moldovenească',
      rtl: 0,
    },
    {
      code: 'mr',
      name: 'Marathi',
      native: 'मराठी',
      rtl: 0,
    },
    {
      code: 'ms',
      name: 'Malay',
      native: 'Bahasa Melayu',
      rtl: 0,
    },
    {
      code: 'mt',
      name: 'Maltese',
      native: 'bil-Malti',
      rtl: 0,
    },
    {
      code: 'my',
      name: 'Burmese',
      native: 'မြန်မာစာ',
      rtl: 0,
    },
    {
      code: 'na',
      name: 'Nauruan',
      native: 'Dorerin Naoero',
      rtl: 0,
    },
    {
      code: 'nb',
      name: 'Norwegian Bokmål',
      native: 'Norsk bokmål',
      rtl: 0,
    },
    {
      code: 'nd',
      name: 'North Ndebele',
      native: 'Sindebele',
      rtl: 0,
    },
    {
      code: 'ne',
      name: 'Nepali',
      native: 'नेपाली',
      rtl: 0,
    },
    {
      code: 'ng',
      name: 'Ndonga',
      native: 'Oshiwambo',
      rtl: 0,
    },
    {
      code: 'nl',
      name: 'Dutch',
      native: 'Nederlands',
      rtl: 0,
    },
    {
      code: 'nn',
      name: 'Norwegian Nynorsk',
      native: 'Norsk nynorsk',
      rtl: 0,
    },
    {
      code: 'no',
      name: 'Norwegian',
      native: 'Norsk',
      rtl: 0,
    },
    {
      code: 'nr',
      name: 'South Ndebele',
      native: 'isiNdebele',
      rtl: 0,
    },
    {
      code: 'nv',
      name: 'Navajo',
      native: 'Diné bizaad',
      rtl: 0,
    },
    {
      code: 'ny',
      name: 'Chichewa',
      native: 'Chi-Chewa',
      rtl: 0,
    },
    {
      code: 'oc',
      name: 'Occitan',
      native: 'Occitan',
      rtl: 0,
    },
    {
      code: 'oj',
      name: 'Ojibwa',
      native: 'ᐊᓂᔑᓈᐯᒧᐎᓐ / Anishinaabemowin',
      rtl: 0,
    },
    {
      code: 'om',
      name: 'Oromo',
      native: 'Oromoo',
      rtl: 0,
    },
    {
      code: 'or',
      name: 'Oriya',
      native: 'ଓଡ଼ିଆ',
      rtl: 0,
    },
    {
      code: 'os',
      name: 'Ossetian / Ossetic',
      native: 'Иронау',
      rtl: 0,
    },
    {
      code: 'pa',
      name: 'Panjabi / Punjabi',
      native: 'ਪੰਜਾਬੀ / पंजाबी / پنجابي',
      rtl: 0,
    },
    {
      code: 'pi',
      name: 'Pali',
      native: 'Pāli / पाऴि',
      rtl: 0,
    },
    {
      code: 'pl',
      name: 'Polish',
      native: 'Polski',
      rtl: 0,
    },
    {
      code: 'ps',
      name: 'Pashto',
      native: 'پښتو',
      rtl: 1,
    },
    {
      code: 'pt',
      name: 'Portuguese',
      native: 'Português',
      rtl: 0,
    },
    {
      code: 'qu',
      name: 'Quechua',
      native: 'Runa Simi',
      rtl: 0,
    },
    {
      code: 'rm',
      name: 'Raeto Romance',
      native: 'Rumantsch',
      rtl: 0,
    },
    {
      code: 'rn',
      name: 'Kirundi',
      native: 'Kirundi',
      rtl: 0,
    },
    {
      code: 'ro',
      name: 'Romanian',
      native: 'Română',
      rtl: 0,
    },
    {
      code: 'ru',
      name: 'Russian',
      native: 'Русский',
      rtl: 0,
    },
    {
      code: 'rw',
      name: 'Rwandi',
      native: 'Kinyarwandi',
      rtl: 0,
    },
    {
      code: 'sa',
      name: 'Sanskrit',
      native: 'संस्कृतम्',
      rtl: 0,
    },
    {
      code: 'sc',
      name: 'Sardinian',
      native: 'Sardu',
      rtl: 0,
    },
    {
      code: 'sd',
      name: 'Sindhi',
      native: 'सिनधि',
      rtl: 0,
    },
    {
      code: 'se',
      name: 'Northern Sami',
      native: 'Sámegiella',
      rtl: 0,
    },
    {
      code: 'sg',
      name: 'Sango',
      native: 'Sängö',
      rtl: 0,
    },
    {
      code: 'sh',
      name: 'Serbo-Croatian',
      native: 'Srpskohrvatski / Српскохрватски',
      rtl: 0,
    },
    {
      code: 'si',
      name: 'Sinhalese',
      native: 'සිංහල',
      rtl: 0,
    },
    {
      code: 'sk',
      name: 'Slovak',
      native: 'Slovenčina',
      rtl: 0,
    },
    {
      code: 'sl',
      name: 'Slovenian',
      native: 'Slovenščina',
      rtl: 0,
    },
    {
      code: 'sm',
      name: 'Samoan',
      native: 'Gagana Samoa',
      rtl: 0,
    },
    {
      code: 'sn',
      name: 'Shona',
      native: 'chiShona',
      rtl: 0,
    },
    {
      code: 'so',
      name: 'Somalia',
      native: 'Soomaaliga',
      rtl: 0,
    },
    {
      code: 'sq',
      name: 'Albanian',
      native: 'Shqip',
      rtl: 0,
    },
    {
      code: 'sr',
      name: 'Serbian',
      native: 'Српски',
      rtl: 0,
    },
    {
      code: 'ss',
      name: 'Swati',
      native: 'SiSwati',
      rtl: 0,
    },
    {
      code: 'st',
      name: 'Southern Sotho',
      native: 'Sesotho',
      rtl: 0,
    },
    {
      code: 'su',
      name: 'Sundanese',
      native: 'Basa Sunda',
      rtl: 0,
    },
    {
      code: 'sv',
      name: 'Swedish',
      native: 'Svenska',
      rtl: 0,
    },
    {
      code: 'sw',
      name: 'Swahili',
      native: 'Kiswahili',
      rtl: 0,
    },
    {
      code: 'ta',
      name: 'Tamil',
      native: 'தமிழ்',
      rtl: 0,
    },
    {
      code: 'te',
      name: 'Telugu',
      native: 'తెలుగు',
      rtl: 0,
    },
    {
      code: 'tg',
      name: 'Tajik',
      native: 'Тоҷикӣ',
      rtl: 0,
    },
    {
      code: 'th',
      name: 'Thai',
      native: 'ไทย / Phasa Thai',
      rtl: 0,
    },
    {
      code: 'ti',
      name: 'Tigrinya',
      native: 'ትግርኛ',
      rtl: 0,
    },
    {
      code: 'tk',
      name: 'Turkmen',
      native: 'Туркмен / تركمن',
      rtl: 0,
    },
    {
      code: 'tl',
      name: 'Tagalog / Filipino',
      native: 'Tagalog',
      rtl: 0,
    },
    {
      code: 'tn',
      name: 'Tswana',
      native: 'Setswana',
      rtl: 0,
    },
    {
      code: 'to',
      name: 'Tonga',
      native: 'Lea Faka-Tonga',
      rtl: 0,
    },
    {
      code: 'tr',
      name: 'Turkish',
      native: 'Türkçe',
      rtl: 0,
    },
    {
      code: 'ts',
      name: 'Tsonga',
      native: 'Xitsonga',
      rtl: 0,
    },
    {
      code: 'tt',
      name: 'Tatar',
      native: 'Tatarça',
      rtl: 0,
    },
    {
      code: 'tw',
      name: 'Twi',
      native: 'Twi',
      rtl: 0,
    },
    {
      code: 'ty',
      name: 'Tahitian',
      native: 'Reo Mā`ohi',
      rtl: 0,
    },
    {
      code: 'ug',
      name: 'Uyghur',
      native: 'Uyƣurqə / ئۇيغۇرچە',
      rtl: 0,
    },
    {
      code: 'uk',
      name: 'Ukrainian',
      native: 'Українська',
      rtl: 0,
    },
    {
      code: 'ur',
      name: 'Urdu',
      native: 'اردو',
      rtl: 1,
    },
    {
      code: 'uz',
      name: 'Uzbek',
      native: 'Ўзбек',
      rtl: 0,
    },
    {
      code: 've',
      name: 'Venda',
      native: 'Tshivenḓa',
      rtl: 0,
    },
    {
      code: 'vi',
      name: 'Vietnamese',
      native: 'Tiếng Việt',
      rtl: 0,
    },
    {
      code: 'vo',
      name: 'Volapük',
      native: 'Volapük',
      rtl: 0,
    },
    {
      code: 'wa',
      name: 'Walloon',
      native: 'Walon',
      rtl: 0,
    },
    {
      code: 'wo',
      name: 'Wolof',
      native: 'Wollof',
      rtl: 0,
    },
    {
      code: 'xh',
      name: 'Xhosa',
      native: 'isiXhosa',
      rtl: 0,
    },
    {
      code: 'yi',
      name: 'Yiddish',
      native: 'ייִדיש',
      rtl: 1,
    },
    {
      code: 'yo',
      name: 'Yoruba',
      native: 'Yorùbá',
      rtl: 0,
    },
    {
      code: 'za',
      name: 'Zhuang',
      native: 'Cuengh / Tôô / 壮语',
      rtl: 0,
    },
    {
      code: 'zh',
      name: 'Chinese',
      native: '中文',
      rtl: 0,
    },
    {
      code: 'zu',
      name: 'Zulu',
      native: 'isiZulu',
      rtl: 0,
    },
  ];
}
